name: statform
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.5
  crypto: ^3.0.3
  uuid: ^4.0.0
  intl: ^0.18.1 # Added for date formatting
  hive: ^2.2.3 # For local database
  hive_flutter: ^1.1.0 # For Flutter integration
  path_provider: ^2.1.1 # For getting application directory

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
