// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ha1JdjXNvYYxdkkySRjIuvdlf0mHkao',
    appId: '1:412088727857:web:f646900a61575d09aa9810',
    messagingSenderId: '412088727857',
    projectId: 'stat-fm8122025',
    authDomain: 'stat-fm8122025.firebaseapp.com',
    storageBucket: 'stat-fm8122025.firebasestorage.app',
    measurementId: 'G-3X0SGYXCQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATqZXuaefzHgUqlzm69sCpjxjcprZfDpI',
    appId: '1:412088727857:android:04df2711682671f6aa9810',
    messagingSenderId: '412088727857',
    projectId: 'stat-fm8122025',
    storageBucket: 'stat-fm8122025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaABEPTEfCxQP5tq2U65uwifNffy3XTjw',
    appId: '1:412088727857:ios:d0f8c7f0dd7c736caa9810',
    messagingSenderId: '412088727857',
    projectId: 'stat-fm8122025',
    storageBucket: 'stat-fm8122025.firebasestorage.app',
    iosBundleId: 'com.example.statform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaABEPTEfCxQP5tq2U65uwifNffy3XTjw',
    appId: '1:412088727857:ios:d0f8c7f0dd7c736caa9810',
    messagingSenderId: '412088727857',
    projectId: 'stat-fm8122025',
    storageBucket: 'stat-fm8122025.firebasestorage.app',
    iosBundleId: 'com.example.statform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ha1JdjXNvYYxdkkySRjIuvdlf0mHkao',
    appId: '1:412088727857:web:6fdbfec9b120552daa9810',
    messagingSenderId: '412088727857',
    projectId: 'stat-fm8122025',
    authDomain: 'stat-fm8122025.firebaseapp.com',
    storageBucket: 'stat-fm8122025.firebasestorage.app',
    measurementId: 'G-S65DGW2ZMY',
  );
}
